bug:
  - "bug"
  - "erro"
  - "fix"
  - "issue"
  - "problema"
  - "error"
enhancement:
  - "enhancement"
  - "feature"
  - "nova funcionalidade"
  - "nova feature"
  - "melhoria"
  - "melhorar"
  - "melhorias"
  - "sugestão"
  - "sugestões"
  - "sugestão de melhoria"
  - "sugestão de funcionalidade"
  - "sugestão de nova funcionalidade"
  - "sugestão de nova feature"
support:
  - "ajuda"
  - "dúvida"
  - "pergunta"
  - "question"
  - "suporte"
  - "support"
  - "help"
  - "help wanted"
  - "need help"
  - "need support"
  - "help me"
  - "me ajude"
  - "me ajuda"