name: Bug
description: Reporte um problema no bot
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## 🐞 Detalhes do bug"
  - type: textarea
    id: problem
    attributes:
      label: "Descreva o problema"
      placeholder: "O que estava tentando fazer? O que deu errado?"
    validations:
      required: true
  - type: input
    id: bot-version
    attributes:
      label: "Versão do bot"