name: No template issues

on:
  issues:
    types: [opened]

jobs:
  close-no-template:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if no template used
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.issue.body;
            const hasTemplate = body.includes("###") || body.includes("- [ ]");
            if(!hasTemplate) {
              await github.issues.createComment({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Olá! Parece que você não usou um dos templates de issue. Por favor, feche essa issue e abra novamente usando o botão `New issue` e escolha a opção correta."
              });

              await github.issues.update({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "closed"
              });
            }