name: Responder a issues com template

on:
  issues:
    types: [opened]

jobs:
  responder:
    runs-on: ubuntu-latest
    steps:
      - name: Responder à issue com comentário e reação
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const token = process.env.GITHUB_TOKEN;
            const octokit = github.getOctokit(token);
            
            const { context } = github;
            const issue_number = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body;

            if (title.includes("bug") || body.includes("### Descreva o problema")) {
              await octokit.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "🐞 Obrigada por reportar um bug! Vamos analisar assim que possível."
              });
              await octokit.rest.reactions.createForIssue({
                owner,
                repo,
                issue_number,
                content: "heart"
              });
            } else if (title.includes("sugestão") || body.includes("### Qual funcionalidade você sugere?")) {
              await octokit.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "✨ Obrigada pela sugestão! Iremos avaliar essa ideia 💜"
              });
              await octokit.rest.reactions.createForIssue({
                owner,
                repo,
                issue_number,
                content: "rocket"
              });
            } else {
              await octokit.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "⚠️ Oi! Parece que sua issue não segue um dos templates. Por favor, edite ou feche e crie novamente usando os botões de template."
              });
              await octokit.rest.reactions.createForIssue({
                owner,
                repo,
                issue_number,
                content: "confused"
              });
            }
