name: Responder a issues com template

on:
  issues:
    types: [opened]

jobs:
  responder:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar conteúdo da issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github, context } = require('@actions/github'); // Ensure proper initialization
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body;
            const issue_number = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            // Exemplo de lógica para diferentes templates
            if (title.includes("bug") || body.includes("### Descreva o problema")) {
              await github.rest.issues.createComment({ // Use github.rest for API calls
                owner,
                repo,
                issue_number,
                body: "🐞 Obrigada por reportar um bug! Vamos analisar assim que possível."
              });
              await github.rest.reactions.createForIssue({
                owner,
                repo,
                issue_number,
                content: "beetle"
              });
            } else if (title.includes("sugestão") || body.includes("### Qual funcionalidade você sugere?")) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "✨ Obrigada pela sugestão! Iremos avaliar essa ideia 💜"
              });
              await github.rest.reactions.createForIssue({
                owner,
                repo,
                issue_number,
                content: "sparkles"
              });
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "⚠️ Oi! Parece que sua issue não segue um dos templates. Por favor, edite ou feche e crie novamente usando os botões de template."
              });
              await github.rest.reactions.createForIssue({
                owner,
                repo,
                issue_number,
                content: "confused"
              });
            }
